### ISSUE TITLE
autodock gpu 실행관련 질문 드립니다.

### ISSUE THREAD

**Issue by Luminol-park** [jongseo-park/AutoDock-GPU_for_ZINC#1]
안녕하세요
작년 여름쯤 운영하시던 티스토리 블로그를 통해 Autodock docker image를 사용하는 과정을 공부했었는데요.
블로그 내용이 정말 알차고 친절하게 정리가 잘 되어 있어서 많은 도움이 되었습니다.
최근 다시 Autodock을 이용해 보고자 블로그를 방문하였으나, 운영 하시던 블로그가 닫혀 있었습니다.
개인적으로 연락을 드려 관련 내용을 질문드리고 싶은데 찾을 수 있는 곳이 깃헙 뿐이라 이슈를 통해 연락드립니다.
혹시, 블로그에 정리되어 있던 Autodock 관련 자료들을 다시 참고하게 도와주실 수 있으신가요?

**Comment by jongseo-park** [comment]
안녕하세요,

제 허접한 글이 도움이 되었다니 기쁩니다.

블로그 글 중에서 autodock-gpu 관련 글들을 다시 공개로 돌려두었습니다.

상세한 사용 방법은 이 repository 의 readme 파일을 참고하시면 되겠습니다.



추가로 질문이 있으시면 언제든지 글을 남겨주세요.

감사합니다.
